-- Reserved for compatibility with existing migration numbering.
-- Demo users are intentionally not removed by schema migration rollback.
-- For local/dev cleanup, run:
--   psql "$DATABASE_URL" -f seeds/dev/demo_users.down.sql
