-- Reserved for compatibility with existing migration numbering.
-- Demo users are intentionally not applied by schema migrations.
-- For local/dev sample credentials, run:
--   psql "$DATABASE_URL" -f seeds/dev/demo_users.up.sql
